language: cpp

compiler: gcc

env:
  - GTS_OPTIONS="-DGTS_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DOpenCV_ROOT_DIR=~/opencv_install/"
  
before_install:
  - pwd
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq cmake qt4-dev-tools > /dev/null
  - sudo apt-get install -qq libunicap2-dev > /dev/null
  - git clone https://github.com/Itseez/opencv.git ~/opencv
  - cd ~/opencv
  - git checkout 2.4.5
  - mkdir ~/opencv/build
  - cd ~/opencv/build
  - cmake -DCMAKE_INSTALL_PREFIX=~/opencv_install/ ../
  - make -j25
  - make install
  - pwd
  - cd /home/travis/dysonltd/gts
  
script:
  - pwd
  - mkdir build
  - cd build
  - cmake $OPTIONS ../
  - cmake --build .
  
# run unit tests
after_script:
  - ./bin/gts_test

branches:
  only:
   - develop
   
notifications:
  email:
    - akram.hussein@dyson.com
  on_success: change
  on_failure: always
